services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: showcase-chariot-prod
    working_dir: /app
    ports:
      - "1000:1000"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_STATE=${NEXT_PUBLIC_STATE}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    command: ["npm", "start", "--", "-p", "1000"]
